apiVersion: apps/v1
kind: Deployment
metadata:
  name: biggie
  labels:
    app: biggie

spec:
  replicas: 50
  selector:
    matchLabels:
      name: biggie
  template:
    metadata:
      labels:
        name: biggie
    spec:
      containers:
      - name: biggie
        image: xornivore/biggie:v2
        env:
        - name: ARG_COUNT
          value: "100"
        - name: ARG_LEN
          value: "1"
        - name: PROC_COUNT
          value: "10"
        resources:
          requests:
            cpu: 1m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi